### ISSUE TITLE
Week 9 ready for review 

### ISSUE THREAD

**Issue by ctkrause** [ctkrause/whatsontap#1]
@pawaitemadisoncollege - week 9 is ready for review. 
This is also the issue for credit regarding week 9 for @AliviaK and @jholmquest 

## What were your key learning points/takeaways?
- It is necessary to build out the entity, dao, and everything before even starting on the API. Learned a little bit about using the annotations to get everything working correctly in terms of routing and whatnot. 

## What challenged you?
- Initially we were challenged with fully comprehending the structure of the project as there was no single resource that fully outlined the way in which everything should look or be setup. Additionally, many examples are using out of date annotations and the xml format. 

## What problems did you solve and what resources did you use to solve them?
- Problems solves including how to build the dao and use hard coded information for testing, how to return json data, and just the basic setup of everything including all the dependencies for the pom and the web xml. 
- https://www.codejava.net/java-ee/web-services/java-crud-restful-web-services-examples-with-jersey-and-tomcat

**Comment by pawaitemadisoncollege** [comment]
Great project idea and a nice completion of week 9!

- [ ] What response types will you support? Just json? html? text? xml?  With the number of resources/operations you are proposing, more types aren't required, but may also be relatively easy to add once you have one type working.   I know xml probably isn't anyone's fav, but it's possible to turn a pojo into xml pretty easily: https://www.tutorialspoint.com/convert-pojo-to-xml-using-the-jackson-library-in-java
